// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzw4R3wPLFt2EoYLWJgVKZjjasUHvVIw',
    appId: '1:1020064149620:web:01b96923881a04f816a121',
    messagingSenderId: '1020064149620',
    projectId: 'moz-nc-tiktok-final',
    authDomain: 'moz-nc-tiktok-final.firebaseapp.com',
    storageBucket: 'moz-nc-tiktok-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbe4BSLjYmciYTVTtfdL1rpPZ6-ItlzN0',
    appId: '1:1020064149620:android:7bcdd6679d9ebdba16a121',
    messagingSenderId: '1020064149620',
    projectId: 'moz-nc-tiktok-final',
    storageBucket: 'moz-nc-tiktok-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBeIh_t2xsFtUalQA0fDpxtIMk3BxtI4',
    appId: '1:1020064149620:ios:179908d73ffdd1f516a121',
    messagingSenderId: '1020064149620',
    projectId: 'moz-nc-tiktok-final',
    storageBucket: 'moz-nc-tiktok-final.appspot.com',
    iosBundleId: 'com.example.ncFlutterTiktokFinal',
  );
}
